# Generated by Django 4.2.4 on 2023-08-27 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('school', '0001_initial'),
        ('evaluation', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizexam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='school.course'),
        ),
        migrations.AddField(
            model_name='quizexam',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='evaluation.quizquestion'),
        ),
        migrations.AddField(
            model_name='quizexam',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quizzes', to='school.section'),
        ),
        migrations.AddField(
            model_name='quizexam',
            name='selected_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selectedchoices', to='evaluation.choice'),
        ),
        migrations.AddField(
            model_name='quizexam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='school.student'),
        ),
        migrations.AddField(
            model_name='appraiserselectedchoice',
            name='appraiser_response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selectedchoices', to='core.appraiserresponse'),
        ),
        migrations.AddField(
            model_name='appraiserselectedchoice',
            name='selected_choice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selectedchoices', to='evaluation.appraiserchoice'),
        ),
        migrations.AddField(
            model_name='appraiserresponse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appraiserresponses', to='school.course'),
        ),
        migrations.AddField(
            model_name='appraiserresponse',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appraiserresponses', to='evaluation.appraiserquestion'),
        ),
        migrations.AddField(
            model_name='appraiserresponse',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appraiserresponses', to='school.section'),
        ),
        migrations.AddField(
            model_name='appraiserresponse',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appraiserresponses', to='school.student'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterUniqueTogether(
            name='quizexam',
            unique_together={('question', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='appraiserresponse',
            unique_together={('question', 'student')},
        ),
    ]
