# Generated by Django 4.2.4 on 2023-08-27 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appraiserresponse',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appraiserresponse',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='appraiserresponse',
            name='week_days',
        ),
        migrations.RemoveField(
            model_name='quizexam',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='quizexam',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='quizexam',
            name='week_days',
        ),
    ]
