# Generated by Django 4.2.4 on 2023-08-27 02:28

from django.db import migrations, models
import school.validators


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='year',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, validators=[school.validators.validate_school_year_at_admin_site]),
        ),
    ]
