# Generated by Django 4.2.4 on 2023-08-30 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_schoolyear_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='school.course'),
            preserve_default=False,
        ),
    ]
