# Generated by Django 4.2.4 on 2023-08-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_attendance_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='school_year',
            field=models.ForeignKey(default=2023, on_delete=django.db.models.deletion.PROTECT, to='school.schoolyear'),
            preserve_default=False,
        ),
    ]
