# Generated by Django 4.2.4 on 2023-10-05 04:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_sectionexam_course_sectionexam_school_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.PositiveSmallIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1, message='Section name cannot be less than 1!')]),
        ),
    ]
