# Generated by Django 4.2.4 on 2023-10-05 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_alter_section_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('classroom', 'classtime'), ('name', 'course')},
        ),
    ]
